import { CategoriaInfo, Produto } from "@/types/product";

export const MOCK_CATEGORIAS: CategoriaInfo[] = [
  {
    slug: "conectividade-satelite",
    nome: "Conectividade & Satélite",
    descricao: "Kits de antenas Starlink fixas, veiculares e marítimas com internet de alta velocidade e baixa latência onde você estiver.",
    imagemCapa: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "mobilidade-eletrica",
    nome: "Mobilidade Elétrica",
    descricao: "Motos e scooters elétricas sustentáveis de alta performance, projetadas para o tráfego urbano e lazer inteligente.",
    imagemCapa: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "cases-protecao",
    nome: "Cases & Proteção Tática",
    descricao: "Maletas estanques, cases rígidas blindadas e soluções de transporte tático anti-impacto para equipamentos sensíveis.",
    imagemCapa: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
  },
  {
    slug: "acessorios-cabos",
    nome: "Acessórios & Cabos",
    descricao: "Roteadores mesh, adaptadores ethernet proprietários, suportes veiculares e fontes de alimentação de alta eficiência.",
    imagemCapa: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
  },
];

export const MOCK_PRODUTOS: Produto[] = [
  {
    id: "e4a78129-b69f-4318-809f-c68e3b5e0001",
    codigoReferencia: "STAR-STD-001",
    nome: "Antena Starlink Standard Kit V4 (Residencial e Comercial)",
    slug: "antena-starlink-standard-kit-v4",
    descricaoCurta: "Internet via satélite de alta velocidade e ultra-baixa latência para locais remotos ou uso residencial avançado.",
    descricaoCompleta: "O Kit Starlink Standard V4 foi projetado para entregar conexão de banda larga de alta velocidade em qualquer lugar do território nacional e internacional. Conta com antena de orientação eletrônica de matriz em fase (phased-array), roteador Wi-Fi 6 de banda tripla e cabos resistentes a intempéries extremas (grau de proteção IP67). Ideal para residências, fazendas, canteiros de obras e empresas que exigem redundância e estabilidade de conexão.",
    preco: 2890.0,
    statusDisponibilidade: "disponivel",
    imagemPrincipal: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: ["https://www.youtube.com/watch?v=dQw4w9WgXcQ"],
    categoria: "conectividade-satelite",
    destaque: true,
    ordemExibicao: 1,
    especificacoes: {
      "Tecnologia de Antena": "Matriz em fase eletrônica (Phased-Array)",
      "Orientação": "Software assistido (Auto-orientação)",
      "Classificação Ambiental": "IP67 Tipo 4 (Resistente a neve, granizo e ventos de até 150 km/h)",
      "Padrão Wi-Fi": "Wi-Fi 6 (802.11ax) Tri-Band 4x4 MU-MIMO",
      "Alcance Wi-Fi": "Até 297 m²",
      "Temperatura Operacional": "-30°C a 50°C",
    },
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-09-20T14:30:00Z",
  },
  {
    id: "f8c92130-c70a-4429-91a0-d79f4c6f0002",
    codigoReferencia: "STAR-MOB-002",
    nome: "Antena Starlink Veicular / High Performance Mobility",
    slug: "antena-starlink-veicular-high-performance",
    descricaoCurta: "Conectividade contínua em movimento para motorhomes, frotas blindadas, veículos utilitários e embarcações.",
    descricaoCompleta: "A Starlink Veicular de Alta Performance foi especificamente desenvolvida para fornecer conectividade sem interrupções mesmo quando o veículo está trafegando em altas velocidades. Com campo de visão mais amplo (140 graus) e recursos avançados de rastreamento por satélite GPS de precisão, garante internet veloz em estradas desertas, expedições off-road e operações críticas.",
    preco: 12490.0,
    statusDisponibilidade: "disponivel",
    imagemPrincipal: "https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1516849841032-87cbac4d88f7?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: [],
    categoria: "conectividade-satelite",
    destaque: true,
    ordemExibicao: 2,
    especificacoes: {
      "Campo de Visão": "140° (Maior abertura para satélites em trânsito)",
      "Uso em Movimento": "Certificado para até 200 km/h",
      "Consumo Médio": "110W - 150W",
      "Suporte de Fixação": "Suporte de montagem de perfil baixo para teto/bagageiro",
      "Proteção Térmica": "Sistema de degelo automático ativo",
    },
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-09-21T09:15:00Z",
  },
  {
    id: "a1b2c3d4-e5f6-47a8-98b9-012345678003",
    codigoReferencia: "MOTO-ELE-003",
    nome: "Moto Elétrica Urbana City Pro 3000W",
    slug: "moto-eletrica-urbana-city-pro-3000w",
    descricaoCurta: "Zero emissão de ruído e carbono, motor elétrico de alto torque, bateria de lítio removível e autonomia de até 90km.",
    descricaoCompleta: "A City Pro 3000W une o design futurista minimalista à eficiência máxima da mobilidade urbana sustentável. Equipada com freios a disco hidráulicos com sistema regenerativo EBS, iluminação full-LED de alta penetração, painel digital TFT com conectividade Bluetooth e suspensão hidráulica invertida dianteira. Carregamento prático em tomada convencional 110V/220V em apenas 5 horas.",
    preco: 18990.0,
    statusDisponibilidade: "disponivel",
    imagemPrincipal: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: [],
    categoria: "mobilidade-eletrica",
    destaque: true,
    ordemExibicao: 3,
    especificacoes: {
      "Potência do Motor": "3000W Brushless no cubo traseiro",
      "Velocidade Máxima": "Até 80 km/h",
      "Autonomia": "Até 90 km por carga completa",
      "Bateria": "Íons de Lítio 72V 35Ah (Removível)",
      "Tempo de Recarga": "4 a 6 horas (Tomada padrão residencial)",
      "Carga Máxima": "160 kg",
    },
    createdAt: "2026-02-01T14:00:00Z",
    updatedAt: "2026-09-22T10:00:00Z",
  },
  {
    id: "b2c3d4e5-f6a7-48b9-a9c0-123456789004",
    codigoReferencia: "SCOOT-XCR-004",
    nome: "Scooter Elétrica Dobrável X-Cruiser 500W",
    slug: "scooter-eletrica-dobravel-x-cruiser",
    descricaoCurta: "Praticidade extrema para o último quilômetro urbano. Quadro de alumínio aeroespacial e dobragem rápida em 3 segundos.",
    descricaoCompleta: "Projetada para fácil transporte em porta-malas, trens ou metrôs. A X-Cruiser possui pneus sólidos anti-furos de 10 polegadas com amortecimento duplo, luz de freio inteligente e 3 modos de pilotagem (Eco, Comfort e Sport). Ideal para deslocamentos rápidos no trânsito das grandes cidades.",
    preco: 3790.0,
    statusDisponibilidade: "indisponivel", // Demonstração clara de produto indisponível
    imagemPrincipal: "https://images.unsplash.com/photo-1597404293560-37aeac0c19a8?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1597404293560-37aeac0c19a8?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: [],
    categoria: "mobilidade-eletrica",
    destaque: false,
    ordemExibicao: 4,
    especificacoes: {
      "Potência": "500W nominal (850W pico)",
      "Velocidade Máxima": "32 km/h",
      "Autonomia": "Até 35 km",
      "Peso": "14.5 kg",
      "Pneus": "10 polegadas reforçados com favo de mel (anti-furo)",
    },
    createdAt: "2026-02-10T16:00:00Z",
    updatedAt: "2026-09-23T08:00:00Z",
  },
  {
    id: "c3d4e5f6-a7b8-49c0-ba01-234567890005",
    codigoReferencia: "CASE-STK-005",
    nome: "Case Rígida Blindada Anti-Impacto para Starlink Standard",
    slug: "case-rigida-blindada-anti-impacto-starlink",
    descricaoCurta: "Proteção de grau militar estanque e impermeável com espuma moldada em CNC sob medida para a antena e acessórios.",
    descricaoCompleta: "A Case Tática Planeta das Cases foi especialmente fabricada em polímero ultra-resistente reforçado para proteger o seu equipamento Starlink durante transportes severos em pickups, barcos, aeronaves ou expedições. Possui válvula de alívio de pressão automática, travas duplas seguras e vedação de borracha impermeável com grau de proteção IP67.",
    preco: 1450.0,
    statusDisponibilidade: "disponivel",
    imagemPrincipal: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: [],
    categoria: "cases-protecao",
    destaque: true,
    ordemExibicao: 5,
    especificacoes: {
      "Material": "Polipropileno injetado de alto impacto com reforço de fibra",
      "Proteção": "IP67 (Submersão temporária e estanque a poeira)",
      "Interior": "Espuma EVA de alta densidade cortada a laser",
      "Válvula de Pressão": "Automática para equalização de altitude em voos",
      "Dimensões": "60cm x 45cm x 25cm",
    },
    createdAt: "2026-03-01T09:30:00Z",
    updatedAt: "2026-09-23T12:00:00Z",
  },
  {
    id: "d4e5f6a7-b8c9-40d1-cb12-345678901006",
    codigoReferencia: "ACC-ETH-006",
    nome: "Adaptador Ethernet Gigabit para Starlink",
    slug: "adaptador-ethernet-gigabit-starlink",
    descricaoCurta: "Acessório original plug-and-play para conexão cabeada RJ45 direta ao seu roteador principal ou switch de rede.",
    descricaoCompleta: "Permite conectar um cabo de rede ethernet RJ45 diretamente ao roteador da Starlink para fornecer link gigabit estável para switches empresariais, computadores gamers, centrais de segurança CFTV e pontos de acesso adicionais sem perdas de latência.",
    preco: 390.0,
    statusDisponibilidade: "disponivel",
    imagemPrincipal: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=85",
    galeriaImagens: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80",
    ],
    videos: [],
    categoria: "acessorios-cabos",
    destaque: false,
    ordemExibicao: 6,
    especificacoes: {
      "Velocidade": "10/100/1000 Mbps Gigabit",
      "Compatibilidade": "Roteador Starlink Standard V2 / V3 / V4",
      "Conexão": "Conector proprietário Starlink para porta RJ45 fêmea",
    },
    createdAt: "2026-03-15T15:20:00Z",
    updatedAt: "2026-09-23T12:00:00Z",
  },
];
